### PR TITLE
Add individual pension insurance section

### PR DESCRIPTION
**Pull request by perlun**
Based on my own discussions and research. There are likely more options available than the ones listed here (for example Alexandria), but I know too little of it to be added at the current time.

### CODE REVIEW

**Comment by perlun** [comment]
Ping @sam-hosseini.

**Comment by sam-hosseini** [comment]
Ciao Per 😊

Thanks for this. I've been busy past few weeks, will take a look into this in the coming weeks. No worries 👍🏼

**Comment by sam-hosseini** [comment]
Hi again Per! 😊

Thank you very much for sending this PR. To maintain the guide's integrity and consistency in language, and to prevent issues that have already confused the readers before, I needed to modify the content. But this section wouldn't have been possible without your contribution and I thank you for that 🙏🏼🥂

I'm gonna merge this now, but if something I've modified is wrong, lemme know here and I'll update.

> There are likely more options available than the ones listed here (for example Alexandria), but I know too little of it to be added at the current time.

No worries about this. Readers are smart and will do their own research and find the best options for themselves 👍🏼

**Comment by perlun** [comment]
Thanks, looks fine even with your changes @sam-hosseini. 👍

**Pull request merged**
