### PR TITLE
Update two sections

### PR DESCRIPTION
**Pull request by xixiaofinland**
Thank you for taking the time to create this PR 💐

I maintain this repository with limited time.

Once you send your PR, I'll review it with respect to the time you spent on creating it.

In return, I expect you to respect my time and make sure all the following conditions are met:

- [x ] I have ensured that my PR respects the [target audience](https://github.com/sam-hosseini/freelancing-in-finland#how-can-this-guide-solve-the-problem) of this guide 👩‍💻👨‍💻
- [x ] I have read this guide from beginning to the end to ensure that my PR respects the integrity of the guide as a whole 💯
- [x ] I have ensured that my PR respects the strong opinions upon which the guide is based. One example would be [this](https://github.com/sam-hosseini/freelancing-in-finland/#take-out-money-from-your-company-in-the-most-tax-optimal-way) 🤝

Thank you!

### CODE REVIEW

**Comment by sam-hosseini** [comment]
Thank you Xi for opening another PR following the guideline 😊

This PR has many problems, and I'm afraid I don't have the time to outline all of them. However, out of respect for the time you spent on creating it, I'll highlight 3 major issues with this PR.

1) These [2 lines](https://github.com/sam-hosseini/freelancing-in-finland/pull/80/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R489-R490) add no value to the guide. As highlighted in the beginning of the guide:

> You are the target audience of this guide if:
> 
> - You are already living in Finland for more than 3 months
> - You are already working as a software developer
> - You want to work as an independent freelance software developer
> - You want to establish a limited liability company to offer your freelance services through it

The target audience of this guide is almost certainly within 18 (most likely just finished high school) and 68 (pension age) age range. This guide is not written to cover everyone's cases, it's deliberately trying to **exclude as many people as possible** from its target audience to then be **extremely useful to a niche group of people**.

Also, the target audience of this guide wants to establish a limited company (Oy) and work through it, so the condition of "You work in your own company" is redundant. This guide was written with the goal of eliminating absolutely all redundant and unnecessary sentences, because, as highlighted in the beginning of the guide:

> In Finland, there are many extensive guides by authorities which have precise information about everything you need to know. The problem is, however, that the target audience of those guides are the general population and **out of every 100 pages, maybe 10 pages are relevant to your situation**.

2) The target audience of this guide are professional (already working) software developers. All developers I've ever worked with were smart analytical people, as required by the job. Therefore, this guide is written for a smart analytical group of people. Throughout the guide, I've never written any instruction on "clicking here/there" because I trusted that my target audience either can use Google Translate or have a Finnish/Swedish coworker help them out. So, the entire instruction of clicking here/there is unnecessary IMO.

3) In your commit message you said:

> "when to buy YEL" is not company revenue related

In your previous message you said: 

> I read through the guideline, checked previous PRs, and made a new one, though **I'm still 100% sure if I did it correctly**.

This is wrong, 100%. YEL income, based on 2023-new-rules, is calculated based on a variety of factors. One of which, and I'd argue the most important one, is your company turnover. If you make 0 money as the target audience of this guide, you don't need to buy YEL insurance and [even if you have one, you can eliminate it](https://www.varma.fi/en/self-employed/yel-insurance/terminating-yel-insurance/#:~:text=Sometimes%2C%20the%20work%20does%20not%20end%20entirely%2C%20but%20decreases%20to%20the%20extent%20that%20your%20work%20input%20falls%20below%20the%20limit%20of%20YEL%20income%20(%E2%82%AC8%2C575.45%20in%202023)). Proof of company turnover in YEL income calculation [from Varma here](https://www.varma.fi/en/self-employed/yel-insurance/determination-of-yel-income/#estimate-the-correct-level-of-yel-income-with-our-calculator:~:text=The%20YEL%20income%20calculator%20gives%20you%20a%20clear%20recommendation%20on%20the%20amount%20of%20YEL%20income%2C%20which%20is%20based%20on%20the%20median%20salary%20in%20your%20sector%20and%20your%20company%E2%80%99s%20turnover.):

> The YEL income calculator gives you a clear recommendation on the amount of YEL income, which is based on the median salary in your sector and your **company’s turnover**.

--

I can't merge this, but I appreciate your effort 😊

**Comment by xixiaofinland** [comment]
Thank you Sam for the clear explanation.  Two points still:

1. You said YEL calculation is company turnover related since the year 2023, I also felt it when chatting with companies handing it. But I can't find this info on any website, for instance not here => https://www.varma.fi/en/self-employed/yel-insurance/yel-obligation/ 

2. The most important message I wanted to convey is that we CAN apply for the start-up grant online in English. It's just the TE website is Finnish&Swedish only. Many people who don't understand Finnish might have missed this.

**Comment by sam-hosseini** [comment]
@allcontributors add @xixiaofinland to contributors for doc

**Comment by sam-hosseini** [comment]
My pleasure 😊

> Many people who don't understand Finnish might have missed this.

That's a valid point. I was under the impression that everyone would understand that it's just the UI that is in Finnish/Swedish, and you can apply for it in English. But even if 1 person would miss the startup grant because of this misunderstanding, I think it's worth adding it to the guide. 

In fact, I just removed ([a1fcc9b](https://github.com/sam-hosseini/freelancing-in-finland/commit/a1fcc9b64bd7ab206e3c33e05b74da9b1ba51eab)) all the references of "which language the UI is available in". Because it was based on your feedback, I added you to the contributors list. Thank you for that 👍🏼

> But I can't find this info on any website

YEL is the most confusing and complex topic I had to deal with while freelancing, so don't be discouraged if you find it hard at first.

**Before 2023** (and it's important to know this), **YEL insurance was just like travel insurance**.

Imagine you're flying to United States. You've heard about crazy healthcare costs if anything happens. You go shop around and find a travel insurance. The travel insurance has 3 levels (Bronze, Silver, Gold), each level covering you up to a point (1 million euros, 2 million euros, 5 million euros). Naturally, if you choose Gold, you pay the most premium, right?

YEL insurance was just like that. Except that instead of insuring your health, you were insuring your social security benefits (sick leave benefit, unemployment benefit, parental leave benefit, disability benefit if it happens, etc). If you wanted to have maximum coverage (similar to Gold) for your social security benefits, you'd pay the maximum contributions (similar to premium). And if you wanted the minimum coverage, you'd pay the minimum contribution.

**After 2023**, Finland implemented new YEL laws and now it's just like any other country. Imagine if you were buying the Bronze level travel insurance for United States, and the travel agency would tell you "Sorry, last year you made 10 million dollars, you MUST buy the Gold level". So, now, depending on how much you made last year in your company, and several other factors, you'd have to choose a YEL coverage that is "appropriate". You're no longer allowed by law to choose whatever coverage you want (before 2023), you have to choose the "appropriate" amount.

This "appropriate" amount is the most confusing thing because so many variables go into it. But the most important variable is **how much your company made or is expected to make**. You can ask for more details from YEL insurance companies 👍🏼

**Comment by xixiaofinland** [comment]
love&peace! Hopefully run into you one day in the small Finnish IT world, Sam.

**Comment by sam-hosseini** [comment]
Thanks Xi, have a great Sunday 🙏🏼

**Comment by perlun** [comment]
I concur with the opinion of @xixiaofinland - thanks for all the work you've put into this, Sam. You don't know how much we appreciate it. 👍 This guide is pretty much "one of its kind" for the Finnish target audience, AFAIK. So in other words, keep up the good work. 😊

**Pull request closed without merging**
