### PR TITLE
Added Toughbyte to brokers

### PR DESCRIPTION
**Pull request by olegp**
Maybe worth adding that I'm the founder of Toughbyte and we've had over 50 contractors work through us so far for end clients such as Nokia, HSL, Yle, Edenred and others.

### CODE REVIEW

**Comment by sam-hosseini** [comment]
@allcontributors add @olegp as a contributor to doc

**Comment by sam-hosseini** [comment]
Thank you Oleg for sending a PR 👍 Good to know that you offer freelance broker services as well 👏🏼

**Comment by olegp** [comment]
Thanks for merging! If you're ever at Maria 01 where our office is, drop by to say hello.

**Comment by sam-hosseini** [comment]
Would be my pleasure! Will do 👍🏼, thanks for the offer!

**Pull request merged**
