### PR TITLE
New broker Added.

### PR DESCRIPTION
**Pull request by aituri**
Thank you for taking the time to create this PR 💐

I maintain this repository with limited time.

Once you send your PR, I'll review it with respect to the time you spent on creating it.

In return, I expect you to respect my time and make sure all the following conditions are met:

- [X] I have ensured that my PR respects the [target audience](https://github.com/sam-hosseini/freelancing-in-finland#how-can-this-guide-solve-the-problem) of this guide 👩‍💻👨‍💻
- [X] I have read this guide from beginning to the end to ensure that my PR respects the integrity of the guide as a whole 💯
- [X] I have ensured that my PR respects the strong opinions upon which the guide is based. One example would be [this](https://github.com/sam-hosseini/freelancing-in-finland/#take-out-money-from-your-company-in-the-most-tax-optimal-way) 🤝

Thank you!

### CODE REVIEW

**Comment by sam-hosseini** [comment]
Hi Petri and thank you for opening this PR! 🙏🏼

I ran the contributors command and updated the auto-generated contributors table in 44b9f0398a07c7efe7dc29ecfa98b50ac838340f, so you can drop 61a43c960e79dc03d7b10ee10ace70018ffe0c76 

Unfortunately I can't merge this PR with its current information. Please provide the following information so I can have a better understanding whether it's useful for the guide:

- Info as to what is Tingent and what is Inkopio
- Info about whether you used their services, how was it, etc
- On the [Requisitions](https://tingent.inkopio.se/vms/requisitionfeed) tab, there's dozens of jobs but a string search for "remote" only returns 1 instance. So this seems to be completely out of the scope of the guide, but let me know if I'm wrong.

Thank you! 👍🏼

**Comment by aituri** [comment]
* Tingent is a broker like the others in the list. Inkopio seems to be a service they're using managing all their gigs and consultants.
* I already managed to get into the process of one of their remote gigs the same day I requested an account. Quite proactive from their side.
* I didn't assume I needed to write instructions for their gig listing system. It's quite intuitive. I guess you receive instructions when your account is approved. I already asked how to find remote gigs, but haven't yet received an answer. I guess you would need to ask that from the gig contact person. Anyway I got a feeling they have lots of remote gigs there. Even though it does not mention 'remote' anywhere in the description.

**Comment by sam-hosseini** [comment]
Thank you for the explanations! 💐

Especially important that you have a personal and positive experience with them 👍🏼

Ok, it could very well be like you said, many brokers don't have proper "tags" but they could have remote gigs and that could be useful for the guide.

You've already contributed before so you're already in the contributors list but thank you again!

If you could please drop 61a43c960e79dc03d7b10ee10ace70018ffe0c76 to resolve the merge conflict, I can then merge it 👍🏼

**Comment by aituri** [comment]
https://github.com/sam-hosseini/freelancing-in-finland/commit/61a43c960e79dc03d7b10ee10ace70018ffe0c76 dropped 👍🏼
Feel free to merge!

**Pull request merged**
