### PR TITLE
Setting up company can be done by accountant

### PR DESCRIPTION
**Pull request by vandelay**
Thank you for taking the time to create this PR 💐

I maintain this repository with limited time.

Once you send your PR, I'll review it with respect to the time you spent on creating it.

In return, I expect you to respect my time and make sure all the following conditions are met:

- [x] I have ensured that my PR respects the [target audience](https://github.com/sam-hosseini/freelancing-in-finland#how-can-this-guide-solve-the-problem) of this guide 👩‍💻👨‍💻
- [x] I have read this guide from beginning to the end to ensure that my PR respects the integrity of the guide as a whole 💯
- [x] I have ensured that my PR respects the strong opinions upon which the guide is based. One example would be [this](https://github.com/sam-hosseini/freelancing-in-finland/#take-out-money-from-your-company-in-the-most-tax-optimal-way) 🤝

Thank you!

### CODE REVIEW

**Comment by sam-hosseini** [comment]
Hi @vandelay and thank you for the PR 🙏🏼

About:

> Some accounting companies (see section below) will set up the company for you, for an additional fee.

This is a repetition, more or less, of:

> You can also give power of attorney in Business Information System to an accountant so that they can establish the company on your behalf.

So it adds no value to the guide IMO.

About:

> This can save you time and also avoid some basic errors such as having too few shares or choosing an inappropriate fiscal year end date. 

This is a low quality sentence. Naturally, when you outsource a job to an accountant, it saves you time, so the *saving time* is implied, no need to mention it again.

Also, mentioning "basic errors such as having too few shares" is not helpful. It's better to mention how many number of shares is ideal for the target audience of this guide and put that as a step in the *Establish your company* section.

About:

> choosing an inappropriate fiscal year end date.

There's no such thing as *inappropriate* fiscal year end date. Anyone is free to choose whatever end date is suitable for them. This is even discussed in "Choose your company's fiscal year ending." sub-step. So this sentence adds no value either.

--
Overall, I'm afraid this PR doesn't add any value and I can't merge it. Thank you for taking the time 👍🏼

**Comment by vandelay** [comment]
@sam-hosseini sure, no problem. 

The reason I added this is that I had feedback from an accountant that many people were turning up with companies that they had set up themselves, but had problems that were expensive to fix (such as those noted). The number of shares and ideal fiscal year dates can of course vary depending on your situation, the point is to get advice before making expensive mistakes, not to prescribe a one-size-fits-none.

**Comment by sam-hosseini** [comment]
Under the step of:

> Establish your company online by filing a startup notification at Business Information System (only available in Finnish)

It is already mentioned that the act of filing the notification can be outsourced to an accountant. And an accountant worth his/her salt will double-check with you about the number of shares or the fiscal year end date.

About:

> not to prescribe a one-size-fits-none.

Strong disagree. This mentality that "it depends on your situation" was a major source of frustration for me when I was figuring stuff out 2 years ago. Every official or seasoned freelancer I was talking to couldn't give me some reasonable estimation, as if it's rocket science or I'm gonna sue them in Supreme Court if they say anything that is not 200% accurate.

Most folks would wanna know the "general, reasonable" information. They can then go and make it specific to themselves by asking from the sources of truth or experts such as lawyers and accountants.

This guide is opinionated for a reason, and that is to never write sentences such as "basic errors such as having too few shares". I can comfortably write in the guide that for the target audience of this guide, 10000 number of shares is a good number. That's it, no need to overcomplicate it, the target audience is already narrow and the suggestions made in the guide are just that, *suggestions*.

**Comment by vandelay** [comment]
Sure, it's your guide, no worries, just add the 10000 shares. Just trying to improve things for people who are using it, after seeing what they do:

- people are making some mistakes when setting up their companies (e.g. 1 share, FY end 1.5)
- and then visiting an accountant who says "I wish you had talked to me first"

so I thought a quick warning would be good for those that are simply following through in sequence - if you don't know exactly what you are doing at this point then maybe get advice. There's more to it than the issues mentioned, so yeah, it doesn't fit your opinionated guide, I guess.

For example, when you give your opinion above "There's no such thing as inappropriate fiscal year end date." I really think this is simply wrong. Picking a date that's not the end of the month can make things harder with reconciling back statements etc. I guess we disagree, but it's your guide, your opinions :)

Thanks for the guide.

**Comment by sam-hosseini** [comment]
@allcontributors add @vandelay to contributors for doc

**Comment by sam-hosseini** [comment]
Ok, you have convinced me and changed my mind, thank you for bringing it to my attention.

> so I thought a quick warning would be good for those that are simply following through in sequence

I didn't know that the sequence of the steps causes the issues you mentioned. I have added the recommendation in c1163628d1c2871e4ad2f4e164b4cfe5ee4a2c8f so that people would know it's always best to do the filing of notification with an accountant who has done it 100s of times to prevent costly mistakes and lots of wasted time 👍🏼

I have also added the step of deciding about number of shares in 3190808c05fe69bf06c6498a9985a5ed4b53f035. I have no idea how I had forgotten to add this step in the first place, thanks for bringing this to my attention as well 👍🏼

> I really think this is simply wrong. Picking a date that's not the end of the month can make things harder with reconciling bank statements etc.

We disagreed before on the mentality of providing suggestions that are too general and ignore the narrow target audience of this guide. I personally love exactly THIS kind of sentences that you just mentioned above. Something like "For A and B reasons, choosing the first day of the month as the end of fiscal year is not good. I recommend you choose last day of the month".

In the end, I noticed this is your 2nd PR and even though it wasn't merged, the commits I added were a direct result of your help, so I thank you for that 🙏🏼😊

**Pull request closed without merging**
